### ISSUE TITLE
Ignore appear/disappear cost in first/last frame by default?

### ISSUE THREAD

**Issue by bentaculum** [funkelab/motile#115]
When setting `Appear`/`Disappear` costs, I would suggest as a default behaviour that these costs are not set for nodes in the first/last frame of the `TrackGraph`. Right now one has to write this explicitly, and not doing so influences e.g. the SSVM fitting. Shall I draft a PR?

**Comment by cmalinmayor** [comment]
Manan and I discussed it and we think its a good idea to have the behavior you suggest as the default (and even potentially as the only option? We couldn't come up with a case where you'd want to pay appear at the beginning/disappear at the end). Jan has the final say, but if you draft a PR I will definitely bring it to his attention!
