### ISSUE TITLE
Write examples and tracking recipes

### ISSUE THREAD

**Issue by bentaculum** [funkelab/motile#17]
- Examples: downloadable notebook + in docs. Options: Parse notebook into sphinx, parse sphinx tutorial into notebook?
- Recipes can be for example:
    - cell tracking
    - single molecule tracking

**Comment by cmalinmayor** [comment]
Tracking recipes will go in [motile_toolbox](https://github.com/funkelab/motile_toolbox), hopefully soon! @bentaculum Please feel free to add some functions, utils, etc. that you've been using to construct motile pipelines, or just open issues with things you think belong there.

Do the current docs satisfy the examples part of this issue @bentaculum?

**Comment by cmalinmayor** [comment]
Excellent, thanks!
