### ISSUE TITLE
AttributeError: 'Solver' object has no attribute 'fit_weights'

### ISSUE THREAD

**Issue by pattonw** [funkelab/motile#76]
I was following the [learning](https://funkelab.github.io/motile/learning.html) guide in the docs and ran into this error. I'm using motile==0.1.3
I pip installed motile, maybe the published docs show features that are not yet available in the pypi package? Installing from github seems to have solved the issue (and downgraded from the version from 0.1.3 to 0.1.2)

**Comment by tlambert03** [comment]
hey @pattonw.  Strange, v0.1.3 on pypi was definitely released from main after https://github.com/funkelab/motile/pull/23 was merged...  let me look into it and I'll cut a new release

**Comment by tlambert03** [comment]
hey @pattonw, I just cut a new release.  At first I (a bit mindlessly) released as v0.1.4, but then I re-released the same version as v0.2.0 since there were enough changes to warrant that bump.  So v0.2.0 should be out in a moment and will solve this.
